---
title: ':CanadianArmy:  | Deployment.'
author: "admin"
date: "2025-04-27"
output: html_document
---

:CanadianArmy:  | Deployment. <br/>
All regiments of the Canadian Army have been officially deployed into battle alongside one of our allies, the United Nations. <br/>

Type of event: PvP Operation. <br/>
Date: 26th April. <br/>
Time: Saturday, April 26, 2025 at 2:00 AM <br/>
Game: https://www.roblox.com/games/123138601927717/R-UN-UNKNOWN-ISLAND-Bunker-Raid
<br/>
Objective: Stated.
<br/>
Attackers: Attack the island with the destroyers, amphibious assault vehicles, helicopters, etc. to take over the control room long enough to start up the nuclear launch sequence.
<br/>
Defenders: Defend the island bunker using the various artillery, helicopters, anti air tools, etc. given and protect the control room at all costs.
<br/>
When the nuclear launch sequence starts, both the teams will have to evacuate the island ASAP.
<br/>
The Canadian Army shall be the attackers.
<br/>
Signed,
<br/>
:CanadianArmy: | Canadian Army HQ and Ownership.
@Canadian Army Personnel 
<br/>
This is a good chance to get medals and awards by the way.
React in attendance. 
<br/>