---
title: "\U0001F341 | Announcement of new ownership Greetings @everyone,"
author: "admin"
date: "2025-04-27"
output: html_document
---

🍁 | Announcement of new ownership
Greetings @everyone, <br/>

Some of you may know me and zee but here's a quick introduction if you don't. Me and zee have owned a 2k+ Canadian army as well as multiple British Army's that have succeeded. We are hoping to strive with this army again and bring it back to life. I hope you guys stick with us, if you don't want to then leave if you want. 
<br/>
Enough talk on that, I want to tell you the strengths we can bring to this Canadian Army. We have great leadership skills, amazing development team, and can't forget the HQ we have. We are still under development of V3, look in ⁠No Access for more updates!
<br/>
I want to thank everyone for being here and I can't wait to strive with this Canadian Army again! If you're wondering yes, we are releasing ads once v3 is done and ready to launch.
<br/>
Signed,
:CanadianArmy: | The Entire HQ and Ownership Team.