---
title: "New Open"
author: "admin"
date: "2025-04-27"
output: html_document
---

NEW CAREER OPENING! <br/>
@everyone <br/><br/>

Careers Programme <br/>
HIRING AUCTION DEVELOPERS! :tools: <br/>
Description <br/>
As our new Auction Devs, you will be tasked to do products that will specifically be listed on Auction in Exclusive Findings! <br/>
If you are a Developer who wants to make a quick extra earning, this is your best shot!
<br/>
Payment <br/>
To compensate for your hard work, you will be rewarded with 70% of the highest bid in the auction! Furthermore, you will still retain full ownership on your own product, which can be auctioned as many times as you wish on EF!
<br/>
Benefits <br/>
You do not need to pay for your own auctions.
A sure-win for you! Once submitted, you just purely need to wait to receive bids.
Bonuses for you! A even bigger W for you.
<br/>
APPLY TODAY! <br/>
DM @iiFire_Law to clarify your questions! <br/>
:link: - https://docs.google.com/forms/d/1j_ufOLqeyFDBuUOjPsWfW7nxrlDpvv-nsRIVBxlmgbw/edit
<br/>
Development Department Management <br/>